name: Main Workflow
on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  Ubuntu:
    name: Add labels to overdue issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.0.6
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
